server:
  port: 8080
  ssl:
    enabled: false  # 本地开发禁用 SSL

delegate:
  subAppId: rdm_1dd2dce363cc4e5fbe951a171a91b825_app
  domain: https://dme.cn-north-4.huaweicloud.com
  domainName: djchanahcjd
  userName: hid_c7i7kks2hw1e4le
  password: admin123456
  endpoint: https://iam.cn-north-4.myhuaweicloud.com
  regionName: cn-north-4
  serviceType: services/dynamic

spring:
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件大小限制
      max-request-size: 20MB    # 总请求大小限制
      enabled: true            # 启用文件上传功能